program test_main
    use complex_sparse_linalg

    implicit none

    type(complex_csr_matrix) :: my_matrix

    ! 1. Read the matrix from the file generated by Python
    call read_matrix('csr_matrix_fortran.txt', my_matrix)

    ! 2. Print the matrix to verify the contents
    call print_matrix(my_matrix)

    ! 3. Free the memory
    call destroy_matrix(my_matrix)

end program test_main


