# this file creates the raising and lowering operators for an n-site system 
import numpy as np

def JW_rl_ops(n_sites):
    I = np.array([[1, 0],[0, 1]], dtype=complex)
    Z = np.array([[1,  0],[0, -1]], dtype=complex)
    
    c_local = np.array([[0, 1],[0, 0]], dtype=complex)       # Annihilation (maps |1> to |0>)
    c_dag_local = np.array([[0, 0],[1, 0]], dtype=complex)   # Creation (maps |0> to |1>)

    l_ops = [] # This will hold annihilation operators c
    r_ops = [] # This will hold creation operators c_dag
    
    for site_i in range(n_sites):
        annihilate = np.array([[1]], dtype=complex)
        create = np.array([[1]], dtype=complex)
        for site_j in range(n_sites):
            # For annihilation operators
            if site_i == site_j:   annihilate = np.kron(annihilate, c_local)
            elif site_j < site_i:  annihilate = np.kron(annihilate, Z)
            else:                  annihilate = np.kron(annihilate, I)
                
            # For creation operators
            if site_i == site_j:   create = np.kron(create, c_dag_local)
            elif site_j < site_i:  create = np.kron(create, Z)
            else:                  create = np.kron(create, I)
                
        l_ops.append(annihilate)
        r_ops.append(create)
        
    ns = l_ops[0].shape[0]
    return (r_ops, l_ops, ns) # r_ops = c_dags, l_ops = c_s

def generate_state(n_sites,excitations):
    ''' 
    Generate a fermionic state vector in the JW basis.
    excitations: a list like [1, 0, 1] indicating which sites have an electron.
    r_ops: the list of raising/creation operators generated by JW_rl_ops.
    '''
    if len(excitations) != n_sites:
        raise ValueError(f"Dimension mismatch! Your model has {n_sites} sites, "
            f"but you provided {len(excitations)} excitations: {excitations}")
    n_states = 2**n_sites
    state = np.zeros(n_states, dtype=complex)
    state[0] = 1 # True vacuum |00...>
    r_ops, l_ops, ns = JW_rl_ops(n_sites)
    for nk, k in enumerate(excitations):
        if k == 1: 
            state = r_ops[nk] @ state # Apply creation operator
    return state



if __name__=='__main__':
    n_sites=4
    r_ops,l_ops=JW_rl_ops(n_sites)
    excitations=[1,0,1,1]
 
    state=generate_state(n_sites,excitations)

    print(state)
    for i in range(n_sites):
        print(state.T.conj()@r_ops[i]@l_ops[i]@state)



