# this file creates the raising and lowering operators for an n-site system 
import numpy as np

def JW_rl_ops(n_sites):
    ''' 
    Creates the matrix representations of the raising and lowering operators for n_sites 
    Fermionic operators using the Jordan-Wigner transformation
    '''
    # Identity matrix  
    I = np.array([[1, 0],[0, 1]], dtype=complex)
    # Pauli-Z Matrix (Z)
    Z = np.array([[1,  0],[0, -1]], dtype=complex)
    # Lowering Operator (S-)
    S_minus = np.array([[0, 0],[1, 0]], dtype=complex)

    ## Build the basis operators; c_k = Z \otimes Z ... C \otimes I ... I, where C is at the k'th position
    l_ops=[]
    r_ops=[]
    for site_i in range(n_sites):
        # Initial lowering operator
        l_op=np.array([[1]], dtype=complex) 
        for site_j in range(n_sites):
            if site_i==site_j:
                l_op=np.kron(l_op,S_minus)
            if site_j<site_i:
                l_op=np.kron(l_op,Z)
            if site_j>site_i:
                l_op=np.kron(l_op,I)
        l_ops.append(l_op)
        r_ops.append(l_op.conj().T)
    #get the dimension of the total Hilbert space
    ns=l_ops[0].shape[0]
    return(r_ops,l_ops,ns)

def generate_state(n_sites,excitations):
    ''' 
    Generate a fermionic state vector in the JW basis.
    excitations: a list like [1, 0, 1] indicating which sites have an electron.
    r_ops: the list of raising/creation operators generated by JW_rl_ops.
    '''
    if len(excitations) != n_sites:
        raise ValueError(f"Dimension mismatch! Your model has {n_sites} sites, "
            f"but you provided {len(excitations)} excitations: {excitations}")
    n_states = 2**n_sites
    # Initialize the state in vaccuo (-1 in JW basis above)
    state=np.zeros(n_states, dtype=complex)
    state[-1]=1 
    r_ops,l_ops=JW_rl_ops(n_sites)
    for nk,k in enumerate(excitations):
        if k==1: #add nk'th excitation
            state=r_ops[nk]@state
    return state



if __name__=='__main__':
    n_sites=4
    r_ops,l_ops=JW_rl_ops(n_sites)
    excitations=[1,0,1,1]
 
    state=generate_state(n_sites,excitations)

    print(state)
    for i in range(n_sites):
        print(state.T.conj()@r_ops[i]@l_ops[i]@state)



