import numpy as np
import os
from scipy.sparse import csr_matrix

# Some useful functions for the HEOM code
# including reade-write functions and naming for FORTRAN executables

def write_sparse(filename,A):
    # Use 1-based indexing for Fortran
    row_ptr = A.indptr + 1
    col_ind = A.indices + 1
    values  = A.data
    with open(filename, "w") as f:
        # Write header, giving the size of the matrix and #nonzeros
        f.write(f"{A.shape[0]} {A.shape[1]} {A.nnz}\n")
        # Write row pointer: n_rows + 1 values
        for val in row_ptr:
            f.write(f"{val:d}\n")
        # Write column indices: nnz values
        for val in col_ind:
            f.write(f"{val:d}\n")
        # Write values with fixed formatting
        for val in values:
            f.write(f"{val.real:22.15e}\n".replace('e','d'))
            f.write(f"{val.imag:22.15e}\n".replace('e','d'))

def write_Zvec(filename, matrix):
    """
    Writes a numpy array to a text file for Fortran to read.
    Alternates real and imaginary parts using D22.15 format.
    """
    # Ensure the input is a complex numpy array
    matrix = np.asarray(matrix, dtype=np.complex128)
    # Create the header string containing the original shape
    # If 1D, it writes e.g., "4". If 2x2, it writes "2 2".
    shape_str = " ".join(map(str, matrix.shape))
    # Flatten the array for the 1D Fortran loop.
    vec = matrix.flatten()
    with open(filename, "w") as f:
        f.write(f"{shape_str}\n") # Write the header (which Fortran read(70, *) will skip)
        f.write(f"{len(vec)}\n") # Write the number of elements
        # Write the alternating real and imaginary parts
        for val in vec:
            # Format nicely to match Fortran's (D22.15) requirements
            # standard python 'e' is replaced with Fortran 'D'
            real_str = f"{val.real:22.15e}".replace('e', 'D')
            imag_str = f"{val.imag:22.15e}".replace('e', 'D')
            
            f.write(f"{real_str}\n")
            f.write(f"{imag_str}\n")

def read_Zvec(filename, size=None):
    with open(filename, "r") as f:
        f.readline()  # Skip the text header line
        n_elements = int(f.readline().strip()) # Read the total number of complex elements
        # Read the numeric data
        content = f.read().replace('D', 'e').split() # .replace('D', 'e') handles the Fortran double precision format
        
    # Convert to complex array
    data = np.array(content, dtype=float)
    # Check if we have the expected number of lines (2 per complex element)
    if len(data) != 2 * n_elements:
        raise ValueError(f"Data mismatch: Expected {2*n_elements} lines, found {len(data)}")
    # Slice Real (indices 0, 2, 4...) and Imag (indices 1, 3, 5...)
    complex_vec = data[0::2] + 1j * data[1::2]
    # Reshape if we know the system size (ns)
    if size is not None and (np.prod(size) == n_elements):
        if isinstance(size, int): # If size is just an int, wrap it in a tuple
            size = (size,)
        return complex_vec.reshape(size)
    return complex_vec

def writeParams(filename,sim): # Writes small parameters into file
    params=sim.params
    bath=sim.bath
    # calculate the total number of time steps for propagation
    nttot = round(params.tmax / params.dt) 
    # get the output ntout (how often to plot)
    custom_dtout = getattr(sim.params, 'dtout', None)
    custom_ntout = getattr(sim.params, 'ntout', None)
    # Check for the 'never' flag first
    if custom_dtout == 'never' or custom_ntout == 'never':
        ntout = max(nttot, 1)
    # If the user provided a physical time interval, convert it to steps
    elif custom_dtout is not None:
        ntout = max(round(custom_dtout / params.dt), 1)
    elif custom_ntout is not None:
        ntout = int(custom_ntout)
    else:
        ntout = int(max(nttot / 1000, 1))
    print(ntout)
    ## Write to the params file for the FORTRAN
    with open(f"{filename}", "w") as f:
        f.write("ns,dt,nttot\n")
        f.write(f"{params.ns:10d}{params.dt:22.15e}{nttot:10d}{ntout:10d}\n".replace('e','d'))
        f.write("/\n")
    return

def FORT_SWITCHES(sim):
    params = sim.params
    ''' Supported compile-time switches (SWITCHES):
       -DPrint_ADOs         Print the ADOs to file every N timesteps
       -DSIA                Use SIA step instead of RK4 step (default)
     '''
    switches = []
    if params.print_ADOs:
        switches.append('Print_ADOs')
    if not params.noSIA:
        switches.append('SIA')
    # sort the switches to be alphabetical
    switches.sort()
    makefile_command= f'SWITCHES=" -D{" -D".join(switches)}"'
    executable_suffix='_'+'_'.join(switches)
    if len(switches) == 0:
        executable_suffix = ''
        makefile_command = 'SWITCHES=""'    
    return makefile_command, executable_suffix

def load_ados(filename='ADOs.dat'):
    """
    Loads ADOs from a .dat file generated by Fortran ADOs_print.
    
    Parameters:
    filename (str): Path to 'ADOs.dat'
    
    Returns:
    times (np.array): 1D array of unique time steps
    ados (np.array): 4D array with shape (N_timesteps, N_ados, ns, ns)
    """
    # Load the raw data (formatted in input_output.f)
    raw_data = np.loadtxt(filename)
    all_times = raw_data[:, 0]
    unique_times = np.unique(all_times)
    nt = len(unique_times)
    n_ados = int(len(all_times)/nt)
    ns =int(np.sqrt(len(raw_data[1,1:])/2))

    ADOs_formatted=np.zeros((nt,n_ados,ns,ns),dtype=complex)
    for it in range(nt):
        for i_ado in range(n_ados):

            re_rho_I = raw_data[it*n_ados+i_ado,1:1+ns**2]
            im_rho_I = raw_data[it*n_ados+i_ado,1+ns**2:]
            rho = re_rho_I + 1.j*im_rho_I

            rho = rho.reshape((ns,ns), order='C')  # reshape to be a density matrix
            ADOs_formatted[it,i_ado,:,:]=rho
    
    return unique_times, ADOs_formatted


if __name__=='__main__':
    

        # Define system size (2x2 density matrix means a 4x4 superoperator)
    N_sys = 2
    N_liouv = N_sys**2

    # Random Complex Density Matrix (rho)
    # Generate random real and imaginary parts between 0.0 and 1.0
    rho_real = np.random.rand(N_sys, N_sys)
    rho_imag = np.random.rand(N_sys, N_sys)
    rho_matrix = rho_real + 1j * rho_imag

    # Random Complex Sparse Matrix (A)
    # Generate a 4x4 dense random complex matrix first
    A_real = np.random.rand(N_liouv, N_liouv)
    A_imag = np.random.rand(N_liouv, N_liouv)
    A_dense = A_real + 1j * A_imag

    # Introduce sparsity by randomly setting ~50% of the elements to exactly zero
    # (This step makes it a "true" sparse matrix for testing)
    sparsity_mask = np.random.rand(N_liouv, N_liouv) > 0.5
    A_dense[sparsity_mask] = 0.0 + 0.0j

    # Convert the masked dense matrix into a Scipy CSR matrix
    A = csr_matrix(A_dense, dtype=np.complex128)


    ## write them all to files
    folder='matrices'
    write_sparse(f"{folder}/csr_matrix_fortran.txt",A)
    write_Zvec(f"{folder}/Fortrho_matrix.txt", rho_matrix)
    print('matrices written, now will do the product')

    # Flatten rho exactly as the text file writer does (Column-major / Fortran order)
    rho_vec = rho_matrix.flatten()

    # Perform the matrix-vector multiplication
    result_vec = A.dot(rho_vec)

    print("==========================================")
    print(" Python Result Vector (A * rho):")
    for i, val in enumerate(result_vec):
        print(f" [{i+1}] {val.real:15.5f}  + {val.imag:15.5f}j")
    print("==========================================")

