#!/usr/bin/env python3
# File: heompy
"""HEOM simulation program.

This program runs an HEOM simulation.
"""

import sys
import os
from pathlib import Path # for touching files
import signal
# Avoiding numpy parallelisation
os.environ['OPENBLAS_NUM_THREADS'] = '1'
os.environ['MKL_NUM_THREADS'] = '1'
import numpy as np
import math as m
import resource


import heom.general as gen
from heom.input import InputObj
from heom.type_dicts import potentials, states, simulations
import heom.dvr as dvr

def main():
    print("=======================================================================")
    print("Running HEOM simulation - WITH NBEADS")
    print("=======================================================================")
    #******************************************************************************
    # Signal handling
    #******************************************************************************
    def signal2exitfile(sig, frame):
        Path("exit").touch()

    signal.signal(signal.SIGINT, signal2exitfile)
    signal.signal(signal.SIGTERM, signal2exitfile)
    #******************************************************************************
    # Handling command line input
    #******************************************************************************
    file_input = sys.argv[1]
    if len(sys.argv) > 2:
        name = sys.argv[2]
        nametag = "_" + name
    else:
        name = ""
        nametag = ""
    inp = InputObj(file_input)

    print("inp.heom_switch")
    print(inp.heom_switch)
    if inp.sim_type=="pyheom":
        main_pyheom(nametag,inp)
    else:
        main_heompy(nametag,inp)

def main_heompy(nametag,inp):
    print("Beginning an HEOM simulation in Python")
    def printADOs(sim):
        for n, rho in sim.ados.items():
            print(n, gen.formatfltshort(np.amax(np.abs(rho))))

    def get_maxADOnum(L,K):
        tot = 0
        for n in range(L+1):
            tot += m.factorial(n+K)/(m.factorial(n)*m.factorial(K))
        tot = int(tot)
        return tot

    def print_status(sim,percent,t):
        if (t<10 or t%percent==0):
            print_timer.end()
            rem_steps = sim.n_t-t
            rem_time = (rem_steps/percent)*print_timer.time()
            steptime = print_timer.start()
            if rem_time > 86400:
                rem_time /= 86400
                timeunit = "days"
            elif rem_time > 3600:
                rem_time /= 3600
                timeunit = "hours"
            elif rem_time > 60:
                rem_time /= 60
                timeunit = "minutes"
            else:
                timeunit = "seconds"

            if (type(sim) is simulations["highT_qm"]) or (type(sim) is simulations["highT_cl"]):
                length_ados = sim.cL
                max_ados = sim.cL
            else:
                length_ados = len(sim.ados)
                max_ados = maxadonum
            message = ("t={:10.2f}, step {:8d} out of {:8d} time steps, "
                    "# ADO = {:4d} out of {:4d}"
                    " - {:6.2f} % finished"
                    " - {:6.2f} " + timeunit + " remaining"
                    ).format(sim.ts[t],t+1, sim.n_t, length_ados,
                            max_ados, 100*(t+1)/sim.n_t, rem_time)
            sys.stdout.write("\r"+message)
            #sys.stdout.flush()

    #******************************************************************************
    # Reporting functions
    #******************************************************************************

    def write_out(sim,t):
        if sim.ts[t]<0:
            sim.write_tcf_q2q2(file_q2_real, file_q2_imag, sim.ts[t])
            sim.write_tcf_q4q4(file_q4_real, file_q4_imag, sim.ts[t])
        if inp.heom_switch in ["tcf_qq","kubo_qq"]:
            if sim.ts[t]<=0:
                sim.write_tcf_q2q2(file_equilibration_real, file_equilibration_imag, sim.ts[t])
            else:
                sim.write_tcf_qq(file_equilibration_real, file_equilibration_imag, sim.ts[t])
        else: # i.e. calculating quadratic TCF
            if sim.ts[t]<=0:
                sim.write_tcf_q4q4(file_equilibration_real, file_equilibration_imag, sim.ts[t])
            else:
                sim.write_tcf_q2q2(file_equilibration_real, file_equilibration_imag, sim.ts[t])

        if inp.write_density!=0:
            sim.write_density(file_density, sim.ts[t])
            if type(sim) is simulations["lowT_qm_ee"]:
                sim.write_density_EE(file_density_EE, sim.ts[t])
        if inp.ado_trend_save == 1:
            sim.write_ado_trend(file_ado_trend, sim.ts[t])

    def write_file_headers(sim):
        if inp.write_density!=0:
            sim.write_position_grid(file_density)
            sim.write_density(file_density, sim.ts[0])
        if type(sim) is simulations["lowT_qm_ee"]:
            sim.write_eval_grid(file_density_EE)
            sim.write_density_EE(file_density_EE, sim.ts[0])

    def check_ado_num(sim,limit):
        if type(sim) is simulations["highT_qm"] or simulations["highT_cl"]:
            pass
        else:
            if len(sim.ados)>=limit:
                print("")
                print("The number of ADOs goes over the limit. Exiting calculation")
                Path("exit").touch()

    #def set_ado_sum_limit(sim,limit=10):
    #    # Default limit is 10 GB
    #    # Numpy needs ~8 B for each float, i.e. 16 B for each complex float
    #    n_numbers = limit*(1024**3)/16
    #    if type(sim) is simulations["lowT_qm_ee"]:
    #        out = int(n_numbers/(sim.n_EE**2))
    #    else:
    #        out = int(n_numbers/(sim.n_q**2))
    #    print("Maximum allowed RAM is {:3f} GB".format(limit))
    #    print("ADO number cutoff is {:3d}".format(out))

    #    return out

    def limit_memory(limit=10):
        n_bytes = limit*(1024**3)
        soft, hard = resource.getrlimit(resource.RLIMIT_AS)
        resource.setrlimit(resource.RLIMIT_AS, (n_bytes, hard))

    #******************************************************************************
    # Setting file names
    #******************************************************************************
    file_density = "rho" + nametag
    file_equilibration_real = "equilibration" + nametag + "_real_au_dat"
    file_equilibration_imag = "equilibration" + nametag + "_imag_au_dat"
    file_q2_real = "q2" + nametag + "_real_au_dat"
    file_q2_imag = "q2" + nametag + "_imag_au_dat"
    file_q4_real = "q4" + nametag + "_real_au_dat"
    file_q4_imag = "q4" + nametag + "_imag_au_dat"
    file_density_EE = "rho_EE"
    file_tcf_qq_real = "tcf_qq" + nametag + "_stnd_real_au_dat"
    file_tcf_qq_imag = "tcf_qq" + nametag + "_stnd_imag_au_dat"
    file_tcf_q2q2_real = "tcf_q2q2" + nametag + "_stnd_real_au_dat"
    file_tcf_q2q2_imag = "tcf_q2q2" + nametag + "_stnd_imag_au_dat"
    file_tcf_qq_kubo_real = "tcf_qq" + nametag + "_kubo_real_au_dat"
    file_tcf_qq_kubo_imag = "tcf_qq" + nametag + "_kubo_imag_au_dat"
    file_tcf_q2q2_kubo_real = "tcf_q2q2" + nametag + "_kubo_real_au_dat"
    file_tcf_q2q2_kubo_imag = "tcf_q2q2" + nametag + "_kubo_imag_au_dat"
    file_potential = "potential"
    file_checkpoint1 = "checkpoint1.pickle"
    file_checkpoint2 = "checkpoint2.pickle"
    file_exit = "exit"
    file_ado_trend = "ado_trend"
    max_RAM_GB = 5
    #******************************************************************************
    # Timing - Start
    #******************************************************************************
    print_timer = gen.Timer()
    timer = gen.Timer()

    #******************************************************************************
    # Initialising objects
    #******************************************************************************
    print("Input eta:",inp.eta)
    pot_orig = potentials[inp.pot_type](inp)
    print("inp bath_type: ",inp.bath_type)

    # Renormalisation coefficient
    if inp.bath_type in {"none"} or inp.a_ren_type=="none":
        # No renormalisation potential
        #pot = potentials["PotEff"](pot_orig,a_ren=inp.eta/inp.dt)
        pot = potentials["PotEff"](pot_orig,a_ren=0)
    elif inp.bath_type == "white":
        #print("creating pot with a_ren: ",inp.eta/inp.dt)
        #pot = potentials["PotEff"](pot_orig,a_ren=inp.eta/inp.dt)
        pot = potentials["PotEff"](pot_orig,a_ren=0)
    elif inp.a_ren_type == "gamma*eta":
        # Correct renormalisation potential
        pot = potentials["PotEff"](pot_orig,a_ren=inp.eta*inp.gamma)
    elif inp.a_ren_type == "eta":
        # Old renormalisation potential
        pot = potentials["PotEff"](pot_orig,a_ren=inp.eta)
    else:
        raise SystemExit("Chosen a_ren_type invalid")

    # The inital state is generated such that it is the equilibrium state of the
    # isolated system in the potential without a_ren, but expressed in the
    # basis of the potential with a_ren
    print("Pot has a_ren:", pot.a_ren)
    state = states[inp.init_state](inp, pot)
    sim = simulations[inp.sim_type](inp, pot, state)
    if inp.sim_type=="heomc":
        pot = potentials["PotEff"](pot_orig,a_ren=inp.eta/inp.dt)
        ham = dvr.hamiltonian(sim.qs,pot,sim.mass)
        ham = sim.evecs[:,:sim.n_EE].T@ham@sim.evecs[:,:sim.n_EE]
        gen.write_cplx_mat("tmp_white_ham",ham)
        quit()


    maxadonum = int(get_maxADOnum(inp.cL, inp.cK))
    #max_ado_num = set_ado_sum_limit(sim,max_RAM_GB)
    limit_memory(max_RAM_GB)


    sim.write_potential_grid(file_potential,pot)

    #******************************************************************************
    # Loading checkpoint (if required)
    #******************************************************************************
    loaded1 = False
    loaded2 = False
    if not (os.path.exists(file_checkpoint1) or os.path.exists(file_checkpoint2)):
        # Writing file headers
        write_file_headers(sim)
    elif inp.load_checkpoint == 1:
        # Loading checkpoint 1
        sim.load_checkpoint(file_checkpoint1)
        loaded1 = True
    elif inp.load_checkpoint == 2:
        # Loading checkpoint 2
        sim.load_checkpoint(file_checkpoint2)
        loaded2 = True

    # Loading checkpoints reinitialises the time grid, such that t0 is the saved
    # time and t1 is the t1 from the current input file

    #******************************************************************************
    # Propagating for t<0
    #******************************************************************************
    stability = True
    exitbool = False
    t = 0
    percent = int(sim.n_t/100)
    if percent==0:
        percent = 1

    write_out(sim,0)
    if sim.ts[0]<0:
        dirprod = False
    else:
        dirprod = True

    if (not dirprod) and (type(sim) is simulations["lowT_qm_ee"]) and (inp.bath_type == "white"):
        tmp_ham = np.copy(sim.ham)
        pot = potentials["PotEff"](pot_orig,a_ren=inp.eta/inp.dt)
        sim.ham = dvr.hamiltonian(sim.qs,pot,sim.mass)
        sim.ham = sim.evecs[:,:sim.n_EE].T@sim.ham@sim.evecs[:,:sim.n_EE]
        sim.iham = (-1j/gen.hbar)*sim.ham

    t_zeropoint = t
    while sim.ts[t]<0 and t<sim.n_t and stability and not exitbool:
        print_status(sim,percent,t)
        sim.propagate(pot, sim.dt)
        t = t+1
        if (not dirprod) and t==t_zeropoint+1 and (inp.bath_type == "white"):
            sim.ham = tmp_ham
            sim.iham = (-1j/gen.hbar)*sim.ham
        #check_ado_num(sim,max_ado_num)
        stability = sim.check_stability(sim.stability_threshold)
        if os.path.exists(file_exit):
            exitbool = True
        if t%sim.tau==sim.t_offset:
            write_out(sim,t)

    #******************************************************************************
    # Saving checkpoint 1
    #******************************************************************************
    if inp.save_checkpoint == 1:
        sim.save_checkpoint(file_checkpoint1, sim.ts[t])

    #******************************************************************************
    # Finding out if second checkpoint is useful
    #******************************************************************************
    if t<sim.n_t:
        check2 = True
    else:
        check2 = False

    #******************************************************************************
    # Making change at t=0
    #******************************************************************************
    if inp.heom_switch=="potential":
        # Potential shift
        pot.switch()
        sim.update_pot(pot)
    elif inp.heom_switch=="tcf_qq" and not loaded2:
        # <qq(t)>
        sim.postmultiply_by_qs()
        # Writing out t=0 tcf
        if abs(sim.ts[t])<1e-7:
            sim.write_tcf_qq(file_tcf_qq_real, file_tcf_qq_imag, sim.ts[t])
    elif inp.heom_switch=="kubo_qq" and not loaded2:
        # Kubo <qq(t)>
        if inp.init_state != "thermal":
            raise SystemExit("Cannot calculate Kubo TCF for this initial state")
        if not inp.sim_type in {"pyheom","highT_qm","lowT_qm","lowT_qm_ee"}:
            raise SystemExit("Cannot calculate Kubo TCF for this simulation type")
        sim.get_kubo_q_state(state)
        # Writing out t=0 tcf
        if abs(sim.ts[t])<1e-7:
            sim.write_tcf_qq(file_tcf_qq_kubo_real, file_tcf_qq_kubo_imag, sim.ts[t])
    elif inp.heom_switch=="tcf_q2q2" and not loaded2:
        # <q^2q^2(t)>
        sim.postmultiply_by_qs()
        sim.postmultiply_by_qs()
        # Writing out t=0 tcf
        if abs(sim.ts[t])<1e-7:
            sim.write_tcf_q2q2(file_tcf_q2q2_real, file_tcf_q2q2_imag, sim.ts[t])
    elif inp.heom_switch=="kubo_q2q2" and not loaded2:
        # Kubo <q^2q^2(t)>
        if inp.init_state != "thermal":
            raise SystemExit("Cannot calculate Kubo TCF for this initial state")
        if not inp.sim_type in {"pyheom","highT_qm","lowT_qm","lowT_qm_ee"}:
            raise SystemExit("Cannot calculate Kubo TCF for this simulation type")
        sim.get_kubo_q2_state(state)
        # Writing out t=0 tcf
        if abs(sim.ts[t])<1e-7:
            sim.write_tcf_q2q2(file_tcf_q2q2_kubo_real, file_tcf_q2q2_kubo_imag, sim.ts[t])

    if (dirprod) and (type(sim) is simulations["lowT_qm_ee"]) and (inp.bath_type == "white"):
        tmp_ham = np.copy(sim.ham)
        pot = potentials["PotEff"](pot_orig,a_ren=inp.eta/inp.dt)
        sim.ham = dvr.hamiltonian(sim.qs,pot,sim.mass)
        sim.ham = sim.evecs[:,:sim.n_EE].T@sim.ham@sim.evecs[:,:sim.n_EE]
        sim.iham = (-1j/gen.hbar)*sim.ham

    #******************************************************************************
    # Propagating for t>0
    #******************************************************************************
    t_zeropoint = t
    while t<sim.n_t and stability and not exitbool:
        print_status(sim,percent,t)
        sim.propagate(pot, sim.dt)
        t = t+1
        if (dirprod) and t==t_zeropoint+1 and (inp.bath_type == "white"):
            sim.ham = tmp_ham
            sim.iham = (-1j/gen.hbar)*sim.ham
        #check_ado_num(sim,max_ado_num)
        stability = sim.check_stability(sim.stability_threshold)
        if os.path.exists(file_exit):
            exitbool = True
        if t%sim.tau==sim.t_offset:
            write_out(sim,t)
            if inp.heom_switch=="tcf_qq":
                sim.write_tcf_qq(file_tcf_qq_real, file_tcf_qq_imag, sim.ts[t])
            elif inp.heom_switch=="kubo_qq":
                sim.write_tcf_qq(file_tcf_qq_kubo_real, file_tcf_qq_kubo_imag, sim.ts[t])
            elif inp.heom_switch=="tcf_q2q2":
                sim.write_tcf_q2q2(file_tcf_q2q2_real, file_tcf_q2q2_imag, sim.ts[t])
            elif inp.heom_switch=="kubo_q2q2":
                sim.write_tcf_q2q2(file_tcf_q2q2_kubo_real, file_tcf_q2q2_kubo_imag, sim.ts[t])

    #******************************************************************************
    # Saving checkpoint 2
    #******************************************************************************
    if (inp.save_checkpoint == 1) and check2:
        sim.save_checkpoint(file_checkpoint2, sim.ts[t])

    #******************************************************************************
    # Timing - End
    #******************************************************************************
    timer.end()
    # Exporting time
    print("")
    print("process time", timer.process())

    Path("time_"+str(int(timer.process()))).touch()

    #******************************************************************************
    # Reporting end of calculation
    #******************************************************************************
    if not stability:
        print("Simulation ended due to instability.")
    elif exitbool:
        print("Simulation was terminated using exit file")
    else:
        print("HEOM simulation finished correctly")

#********************************************************************************
#********************************************************************************
#********************************************************************************
# Version for pyheom/libheom version due to Ikeda and Scholes
#********************************************************************************
#********************************************************************************
#********************************************************************************
#
#def main_pyheom(nametag,inp):
#    print("Beginning an HEOM simulation in Python and C++")
#    def printADOs(sim):
#        for n, rho in sim.ados.items():
#            print(n, gen.formatfltshort(np.amax(np.abs(rho))))
#
#    def get_maxADOnum(L,K):
#        tot = 0
#        for n in range(L+1):
#            tot += m.factorial(n+K)/(m.factorial(n)*m.factorial(K))
#        return tot
#
#    def print_status(sim,percent,t):
#        if (t<10 or t%percent==0):
#            print_timer.end()
#            rem_steps = sim.n_t-t
#            rem_time = (rem_steps/percent)*print_timer.time()
#            steptime = print_timer.start()
#            if rem_time > 86400:
#                rem_time /= 86400
#                timeunit = "days"
#            elif rem_time > 3600:
#                rem_time /= 3600
#                timeunit = "hours"
#            elif rem_time > 60:
#                rem_time /= 60
#                timeunit = "minutes"
#            else:
#                timeunit = "seconds"
#
#            if type(sim) is simulations["highT_qm"] or simulations["highT_cl"]:
#                length_ados = sim.cL
#                max_ados = sim.cL
#            else:
#                length_ados = len(sim.ados)
#                max_ados = maxadonum
#            message = ("t={:10.2f}, step {:8d} out of {:8d} time steps, "
#                    "# ADO = {:4d} out of {:4d}"
#                    " - {:6.2f} % finished"
#                    " - {:6.2f} " + timeunit + " remaining"
#                    ).format(sim.ts[t],t+1, sim.n_t, length_ados,
#                            max_ados, 100*(t+1)/sim.n_t, rem_time)
#            sys.stdout.write("\r"+message)
#            #sys.stdout.flush()
#    def write_file_headers(sim):
#        #sim.write_position_grid(file_density)
#        #sim.write_density(file_density, sim.ts[0],sim.rho0)
#        if type(sim) is simulations["lowT_qm_ee"] or simulations["pyheom"]:
#            sim.write_eval_grid(file_density_EE)
#            sim.write_density_EE(file_density_EE, sim.ts[0], sim.rho0)
#
#    #******************************************************************************
#    # Setting file names
#    #******************************************************************************
#    file_density = "rho" + nametag
#    file_equilibration_real = "equilibration" + nametag + "_real_au_dat"
#    file_equilibration_imag = "equilibration" + nametag + "_imag_au_dat"
#    file_q2_real = "q2" + nametag + "_real_au_dat"
#    file_q2_imag = "q2" + nametag + "_imag_au_dat"
#    file_q4_real = "q4" + nametag + "_real_au_dat"
#    file_q4_imag = "q4" + nametag + "_imag_au_dat"
#    file_density_EE = "rho_EE"
#    file_tcf_qq_real = "tcf_qq" + nametag + "_stnd_real_au_dat"
#    file_tcf_qq_imag = "tcf_qq" + nametag + "_stnd_imag_au_dat"
#    file_tcf_q2q2_real = "tcf_q2q2" + nametag + "_stnd_real_au_dat"
#    file_tcf_q2q2_imag = "tcf_q2q2" + nametag + "_stnd_imag_au_dat"
#    file_tcf_qq_kubo_real = "tcf_qq" + nametag + "_kubo_real_au_dat"
#    file_tcf_qq_kubo_imag = "tcf_qq" + nametag + "_kubo_imag_au_dat"
#    file_tcf_q2q2_kubo_real = "tcf_q2q2" + nametag + "_kubo_real_au_dat"
#    file_tcf_q2q2_kubo_imag = "tcf_q2q2" + nametag + "_kubo_imag_au_dat"
#    file_potential = "potential"
#    file_checkpoint1 = "checkpoint1.pickle"
#    file_checkpoint2 = "checkpoint2.pickle"
#    file_exit = "exit"
#    file_ado_trend = "ado_trend"
#    max_ado_num = 5000
#    #******************************************************************************
#    # Timing - Start
#    #******************************************************************************
#    print_timer = gen.Timer()
#    timer = gen.Timer()
#
#    #******************************************************************************
#    # Initialising objects
#    #******************************************************************************
#    pot = potentials[inp.pot_type](inp)
#    # If we are to truly start from a factorised state, then the initial state of
#    # the system must not know about the effective potential due to the bath
#
#    # Renormalisation coefficient
#    if inp.bath_type=="none" or inp.a_ren_type=="none":
#        # No renormalisation potential
#        pot = potentials["PotEff"](pot,a_ren=0)
#    elif inp.a_ren_type == "gamma*eta":
#        # Correct renormalisation potential
#        pot = potentials["PotEff"](pot,a_ren=inp.eta*inp.gamma)
#    elif inp.a_ren_type == "eta":
#        # Old renormalisation potential
#        pot = potentials["PotEff"](pot,a_ren=inp.eta)
#    else:
#        raise SystemExit("Chosen a_ren_type invalid")
#
#    state = states[inp.init_state](inp, pot)
#    # If the initial state is to be in equilibrium with Z_eff
#    #sim = simulations[inp.sim_type](inp, pot, state)
#    print("Creating system object")
#    sim = simulations["pyheom"](inp, pot, state)
#
#    maxadonum = int(get_maxADOnum(inp.cL, inp.cK))
#    print("Writing potential grid")
#    sim.write_potential_grid(file_potential,pot)
#
#    #******************************************************************************
#    # Loading checkpoint (if required)
#    #******************************************************************************
#    loaded1 = False
#    loaded2 = False
#    if not (os.path.exists(file_checkpoint1) or os.path.exists(file_checkpoint2)):
#        # Writing file headers
#        write_file_headers(sim)
#    elif inp.load_checkpoint == 1:
#        # Loading checkpoint 1
#        sim.load_checkpoint(file_checkpoint1)
#        loaded1 = True
#    elif inp.load_checkpoint == 2:
#        # Loading checkpoint 2
#        sim.load_checkpoint(file_checkpoint2)
#        loaded2 = True
#
#    # Loading checkpoints reinitialises the time grid, such that t0 is the saved
#    # time and t1 is the t1 from the current input file
#
#    #******************************************************************************
#    # Propagating for t<0
#    #******************************************************************************
#    stability = True
#    exitbool = False
#    t = 0
#    percent = int(sim.n_t/100)
#    if percent==0:
#        percent = 1
#    current_t0 = sim.ts[0]
#
#    def write_out(t,rho):
#        time = t+current_t0
#        #sim.write_density(file_density,time,rho)
#        if time<=0:
#            print("TEST")
#            sim.write_tcf_q2q2(file_q2_real, file_q2_imag, sim.ts[t])
#            print("END TEST")
#            sim.write_tcf_q4q4(file_q4_real, file_q4_imag, sim.ts[t])
#        if inp.heom_switch in ["tcf_qq","kubo_qq"]:
#            if time<=0:
#                sim.write_tcf_q2q2(file_equilibration_real, file_equilibration_imag, time, rho)
#            else:
#                sim.write_tcf_qq(file_equilibration_real, file_equilibration_imag, time, rho)
#        else:
#            if time<=0:
#                sim.write_tcf_q4q4(file_equilibration_real, file_equilibration_imag, time, rho)
#            else:
#                sim.write_tcf_q2q2(file_equilibration_real, file_equilibration_imag, time, rho)
#        if type(sim) in [simulations["lowT_qm_ee"],simulations["pyheom"]]:
#            sim.write_density_EE(file_density_EE, time, rho)
#        #if inp.ado_trend_save == 1:
#        #    sim.write_ado_trend(file_ado_trend, t, rho)
#
#
#    while sim.ts[t]<0 and t<sim.n_t and stability and not exitbool:
#        #print_status(sim,percent,t)
#        #sim.propagate(pot, sim.dt)
#        t = t+1
#        #check_ado_num(sim,max_ado_num)
#        #stability = sim.check_stability(sim.stability_threshold)
#        #if os.path.exists(file_exit):
#        #    exitbool = True
#        #if t%sim.tau==sim.t_offset:
#        #    write_out(sim,t)
#
#    n_t_negative = t
#
#    if n_t_negative > 0:
#        print(f"Propagating for negative t: {n_t_negative}")
#        sim.h.time_evolution(sim.dt,n_t_negative,write_out,sim.tau)
#
#    #******************************************************************************
#    # Saving checkpoint 1
#    #******************************************************************************
#    #if inp.save_checkpoint == 1:
#    #    sim.save_checkpoint(file_checkpoint1, sim.ts[t])
#    #
#    #******************************************************************************
#    # Finding out if second checkpoint is useful
#    #******************************************************************************
#    #if t<sim.n_t:
#    #    check2 = True
#    #else:
#    #    check2 = False
#    #
#    #******************************************************************************
#    # Making change at t=0
#    #******************************************************************************
#    #******************************************************************************
#    # NB: pyheom outputs initial state (t=0), which is why it is commented out
#    #******************************************************************************
#    #******************************************************************************
#    if inp.heom_switch=="potential":
#        # Potential shift
#        pot.switch()
#        sim.update_pot(pot)
#    elif inp.heom_switch=="tcf_qq" and not loaded2:
#        # <QQ(t)>
#        sim.postmultiply_by_qs()
#        # Writing out t=0 tcf
#        #if abs(sim.ts[t])<1e-7:
#        #    sim.write_tcf_qq(file_tcf_qq_real, file_tcf_qq_imag, sim.ts[t],
#        #            sim.h.get_rho())
#    elif inp.heom_switch=="kubo_qq" and not loaded2:
#        if inp.init_state != "thermal":
#            raise SystemExit("Cannot calculate Kubo TCF for this initial state")
#        if not inp.sim_type in {"pyheom","highT_qm","lowT_qm","lowT_qm_ee"}:
#            raise SystemExit("Cannot calculate Kubo TCF for this simulation type")
#        sim.get_kubo_q_state(state)
#        # Kubo <QQ(t)>
#        # Writing out t=0 tcf
#        #if abs(sim.ts[t])<1e-7:
#        #    sim.write_tcf_qq(file_tcf_qq_kubo_real, file_tcf_qq_kubo_imag,
#        #            sim.ts[t], sim.h.get_rho())
#    elif inp.heom_switch=="tcf_q2q2" and not loaded2:
#        # <Q^2Q^2(t)>
#        sim.postmultiply_by_qs()
#        sim.postmultiply_by_qs()
#        # Writing out t=0 tcf
#        #if abs(sim.ts[t])<1e-7:
#        #    sim.write_tcf_q2q2(file_tcf_q2q2_real, file_tcf_q2q2_imag, sim.ts[t], sim.h.get_rho())
#    elif inp.heom_switch=="kubo_q2q2" and not loaded2:
#        if inp.init_state != "thermal":
#            raise SystemExit("Cannot calculate Kubo TCF for this initial state")
#        if not inp.sim_type in {"pyheom","highT_qm","lowT_qm","lowT_qm_ee"}:
#            raise SystemExit("Cannot calculate Kubo TCF for this simulation type")
#        sim.get_kubo_q2_state(state)
#        # Kubo <QQ(t)>
#        ## Writing out t=0 tcf
#        #if abs(sim.ts[t])<1e-7:
#        #    sim.write_tcf_q2q2(file_tcf_q2q2_kubo_real, file_tcf_q2q2_kubo_imag, sim.ts[t], sim.h.get_rho())
#
#
#    #******************************************************************************
#    # Propagating for t>0
#    #******************************************************************************
#    current_t0 = sim.ts[t]
#    while t<sim.n_t and stability and not exitbool:
#        #print_status(sim,percent,t)
#        #sim.propagate(pot, sim.dt)
#        t = t+1
#        #check_ado_num(sim,max_ado_num)
#        #stability = sim.check_stability(sim.stability_threshold)
#        #if os.path.exists(file_exit):
#        #    exitbool = True
#        #if t%sim.tau==sim.t_offset:
#        #    write_out(sim,t)
#        #    if inp.heom_switch==2:
#        #        sim.write_tcf_qq(file_tcf_qq_real, file_tcf_qq_imag, sim.ts[t])
#        #    elif inp.heom_switch==3:
#        #        sim.write_tcf_qq(file_tcf_qq_kubo_real, file_tcf_qq_kubo_imag, sim.ts[t])
#        #    elif inp.heom_switch==4:
#        #        sim.write_tcf_q2q2(file_tcf_q2q2_real, file_tcf_q2q2_imag, sim.ts[t])
#        #    elif inp.heom_switch==5:
#        #        sim.write_tcf_q2q2(file_tcf_q2q2_kubo_real, file_tcf_q2q2_kubo_imag, sim.ts[t])
#    #
#    # HERE COMES A DEFINITION OF A NEW WRITE OUT FUNCTION!!!!!!!!!!!!!!!!!!!!!!!!
#    def write_out2(t,rho):
#        write_out(t,rho)
#        time = t+current_t0
#        if inp.heom_switch=="tcf_qq":
#            sim.write_tcf_qq(file_tcf_qq_real, file_tcf_qq_imag, time, rho)
#        elif inp.heom_switch=="kubo_qq":
#            sim.write_tcf_qq(file_tcf_qq_kubo_real, file_tcf_qq_kubo_imag, time, rho)
#        elif inp.heom_switch=="tcf_q2q2":
#            sim.write_tcf_q2q2(file_tcf_q2q2_real, file_tcf_q2q2_imag, time, rho)
#        elif inp.heom_switch=="kubo_q2q2":
#            sim.write_tcf_q2q2(file_tcf_q2q2_kubo_real, file_tcf_q2q2_kubo_imag, time, rho)
#        #if inp.ado_trend_save == 1:
#        #    sim.write_ado_trend(file_ado_trend, t, rho)
#    #
#    n_t_positive = t-n_t_negative
#    if n_t_positive > 0:
#        print(f"Propagating for positive t: {n_t_positive}")
#        sim.h.time_evolution(sim.dt,n_t_positive,write_out2,sim.tau)
#
#    #******************************************************************************
#    # Saving checkpoint 2
#    #******************************************************************************
#    #if (inp.save_checkpoint == 1) and check2:
#    #    sim.save_checkpoint(file_checkpoint2, sim.ts[t])
#    #
#    #******************************************************************************
#    # Timing - End
#    #******************************************************************************
#    timer.end()
#    # Exporting time
#    print("")
#    print("process time", timer.process())
#
#    Path("time_"+str(int(timer.process()))).touch()
#
#    #******************************************************************************
#    # Reporting end of calculation
#    #******************************************************************************
#    if not stability:
#        print("Simulation ended due to instability.")
#    elif exitbool:
#        print("Simulation was terminated using exit file")
#    else:
#        print("HEOM simulation finished correctly")


if __name__=="__main__":
    main()
